#!/bin/bash
# shellcheck shell=bash

# GPU支持检测
if ls /dev/dri/renderD* 1> /dev/null 2>&1 && [ -z "${DISABLE_DRI}" ] && ! which nvidia-smi; then
  HW3D="-hw3d"
fi

# 渲染设备设置
: "${DRINODE:=/dev/dri/renderD128}"

# 分辨率处理逻辑
# 统一分辨率配置管理
: ${RESOLUTION:=1920x1080}
: ${RESIZE_MODE:=${RESOLUTION:+scale}}
RESIZE_MODE="${RESIZE_MODE:-remote}"

exec s6-setuidgid abc \
  /usr/local/bin/Xvnc $DISPLAY \
    ${HW3D} \
    -PublicIP 127.0.0.1 \
    -drinode ${DRINODE} \
    -disableBasicAuth \
    -SecurityTypes None \
    -AlwaysShared \
    -http-header Cross-Origin-Embedder-Policy=require-corp \
    -http-header Cross-Origin-Opener-Policy=same-origin \
    -geometry ${RESOLUTION} \
    -sslOnly 0 \
    -RectThreads 0 \
    -websocketPort 6901 \
    -interface 0.0.0.0 \
    -Log *:stdout:10