name: Docker Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - README.md

env:
  IMAGE_NAME: baidunetdisk-docker

jobs:
  job:
    name: Docker Hub Description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Description
        run: |
          description=$(curl "https://api.github.com/repos/${{ github.repository }}" | jq -r ".description")
          echo "DESCRIPTION=${description}" >> "$GITHUB_ENV"

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          short-description: ${{ env.DESCRIPTION }}
          readme-filepath: ./README.md
