name: test

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
  
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - "main"
  #     - "develop"
  #   paths-ignore:
  #     - ".github/**"
  #     - "docs/**"
  #     - "**.md"

env:
  BUILD_TAG: localhost:5000/yucatovo/baidunetdisk-docker:test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: ["linux/amd64", "linux/arm64"]
    services:
      registry:
        image: registry:3.0.0-alpha.1
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set the value
        id: set-vars
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> "$GITHUB_ENV"
          echo "ARCH=${platform//linux\//}" >> "$GITHUB_ENV"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
          platforms: ${{ matrix.platform }}

      - name: Build
        uses: docker/bake-action@v4
        with:
          push: true
          targets: ${{ env.TARGET }}
        env:
          DEFAULT_TAG: ${{ env.BUILD_TAG }}-${{ env.PLATFORM_PAIR }}

      - name: Test
        run: |
          docker run --rm  --platform "${{ matrix.platform }}" alpine:edge echo hello
